server:
  port: 8090
spring:
  devtools:
    livereload: 
      enabled : true
    restart: 
      enabled : true
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/myhomepage?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true