server:
  port: 8090
  
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload: 
      enabled : true
    restart: 
      enabled : true
  datasource:
    username: ENC(V6atDWafbFXYnKSs3cugWQ==)
    password: ENC(tS9HZ5yynkm3zkXa69C/eg==)
    url: ENC(n31JYKWsmNglurbpvPgPqYW5RT1wQ2TlPpiCbNGLv9Fbi9wdmjjXaHOZrgTiQc41tn+1KiUjjBXle+jqhMsm4Atmkp4LJaTkL/jp0nE8cwqOuDJolKYuEe/ATvDa/v2HoJBx11wXmGI=)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cloud:
  aws:
    object-storage:
      endPoint: ENC(44TdIqA9TwBnbCEXOqNWY0lP+2HXczAT3VZ7QyWzP40bGHKfPvb7tOiSr1k5DHRhgWSIrRBqWOE=)
      bucketName: ENC(OtQpOcNPikoZiurBVHrQsA==)
      path:
        attachment: dev/attachment_files
        viewImage: dev/view_image_files
    regionName: ENC(1mpofuyo2JSb3cxQ5LXGz2Km0g1DhsiB)
    credentials:
      accessKey: ENC(Dha84k7jTOoJFh17fJWm58w3/XNlsRO6mgWznTXuDgU=)
      secretKey: ENC(R4Qc+4PCIVjC1TmZH7lOSEt9dqmC+0CuEhMe1G11tQfKKCU8rvUmfzD+C2pSCR/1TVHIJZaD9NQ=)
